### ISSUE TITLE
SQLiteCipher - SpatiaLite question

### ISSUE THREAD

**Issue by Bezzu** [sevar83/android-spatialite#2]
Hi,
I use the SQLiteCipher (Zetetic) android library to manage the SQlite databases and now I 'm trying  to integrate the spatialite part. Why do you deprecate the SQLiteCipher in your new release? 

Thank you in advance

**Comment by sevar83** [comment]
Hi, from SQLiteCipher I used only the wrapper classes but not the encryption. It was entirely cut out. The reason for migration to different wrapper approach is mentioned briefly in the readme. I could add that the original SQLiteCipher project supports very very ancient API levels (something around API7). In order to achieve the backward compatibility, they use a very old snapshot of the SQLite AOSP classes which is quite messy in comparison to the newer (API21+) AOSP classes used now. That old codebase were a pain to maintain and was a potential nest of hard to fix bugs. The newer wrapper is much cleaner, supports connection pooling and more stuff that I don't recall atm. The migration was not exactly a deprecation. It was mainly seen as a change of package names. The SQLite implementation is pretty much the same. And both have *no* encryption support included. I'm afraid it won't be possible to use both SQLCipher and Spatialite at the same time in the same database. If you got more questions and I'm here.
